# Generated by Django 5.1.1 on 2025-07-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('car_type', models.CharField(max_length=100)),
                ('car_number', models.CharField(max_length=50)),
            ],
        ),
    ]
